using UnityEngine;
using UnityEngine.Events;
using UnityEngine.UI;

namespace AnimalFarm.UI
{
    /// <summary>
    /// Shared look for every code-built panel (beauty pass). Rounded 9-slice
    /// sprites live in Resources/UIPlaceholder (generated by the art tool);
    /// everything degrades gracefully to flat color if a sprite is missing.
    /// Use these helpers instead of raw Images/Buttons in all new UI.
    /// </summary>
    public static class UIStyle
    {
        // ---- palette --------------------------------------------------------
        public static readonly Color PanelBg = new Color(0.115f, 0.125f, 0.155f, 0.97f);
        public static readonly Color PanelBgLight = new Color(0.17f, 0.18f, 0.22f, 0.98f);
        public static readonly Color ButtonBg = new Color(0.225f, 0.235f, 0.29f, 1f);
        public static readonly Color ButtonHover = new Color(0.30f, 0.31f, 0.38f, 1f);
        public static readonly Color ButtonPressed = new Color(0.17f, 0.175f, 0.22f, 1f);
        public static readonly Color Gold = new Color(1f, 0.84f, 0.45f, 1f);
        public static readonly Color GoldDim = new Color(0.72f, 0.60f, 0.33f, 1f);
        public static readonly Color Cream = new Color(0.95f, 0.94f, 0.88f, 1f);
        public static readonly Color Grey = new Color(0.62f, 0.63f, 0.66f, 1f);
        public static readonly Color Danger = new Color(0.78f, 0.32f, 0.28f, 1f);
        public static readonly Color BarBg = new Color(0.08f, 0.085f, 0.11f, 1f);

        private static Sprite _panel, _button, _bar;
        private static bool _loaded;

        public static Sprite PanelSprite { get { LoadOnce(); return _panel; } }
        public static Sprite ButtonSprite { get { LoadOnce(); return _button; } }
        public static Sprite BarSprite { get { LoadOnce(); return _bar; } }

        private static void LoadOnce()
        {
            if (_loaded) return;
            _loaded = true;
            _panel = Resources.Load<Sprite>("UIPlaceholder/ui_panel");
            _button = Resources.Load<Sprite>("UIPlaceholder/ui_button");
            _bar = Resources.Load<Sprite>("UIPlaceholder/ui_bar");
        }

        // ---- builders -------------------------------------------------------

        /// <summary>Rounded panel image on a fresh RectTransform.</summary>
        public static RectTransform MakePanel(Transform parent, string name, Color? bg = null)
        {
            var go = new GameObject(name);
            var rt = go.AddComponent<RectTransform>();
            rt.SetParent(parent, false);
            var img = go.AddComponent<Image>();
            ApplyPanel(img, bg);
            return rt;
        }

        /// <summary>Restyles an existing Image as a rounded panel.</summary>
        public static void ApplyPanel(Image img, Color? bg = null)
        {
            if (img == null) return;
            if (PanelSprite != null) { img.sprite = PanelSprite; img.type = Image.Type.Sliced; }
            img.color = bg ?? PanelBg;
        }

        /// <summary>Standard rounded button with label. Caller sizes the RectTransform.</summary>
        public static Button MakeButton(Transform parent, string label, UnityAction onClick,
            int fontSize = 26, Color? bg = null)
        {
            var go = new GameObject("Button_" + label);
            var rt = go.AddComponent<RectTransform>();
            rt.SetParent(parent, false);

            var img = go.AddComponent<Image>();
            if (ButtonSprite != null) { img.sprite = ButtonSprite; img.type = Image.Type.Sliced; }
            img.color = Color.white;

            var button = go.AddComponent<Button>();
            button.targetGraphic = img;
            StyleButton(button, bg);
            if (onClick != null) button.onClick.AddListener(onClick);

            var text = UIRoot.MakeText(rt, "Label", fontSize, TextAnchor.MiddleCenter, Cream);
            text.text = label;
            var trt = text.rectTransform;
            trt.anchorMin = Vector2.zero; trt.anchorMax = Vector2.one;
            trt.offsetMin = Vector2.zero; trt.offsetMax = Vector2.zero;
            return button;
        }

        /// <summary>Applies the standard ColorBlock (optionally around a custom base).</summary>
        public static void StyleButton(Button button, Color? bg = null)
        {
            if (button == null) return;
            Color baseCol = bg ?? ButtonBg;
            var colors = button.colors;
            colors.normalColor = baseCol;
            colors.highlightedColor = Color.Lerp(baseCol, Color.white, 0.18f);
            colors.pressedColor = Color.Lerp(baseCol, Color.black, 0.25f);
            colors.selectedColor = Color.Lerp(baseCol, Color.white, 0.10f);
            colors.disabledColor = new Color(baseCol.r, baseCol.g, baseCol.b, 0.4f);
            colors.fadeDuration = 0.08f;
            button.colors = colors;
            if (button.targetGraphic is Image img && ButtonSprite != null)
            { img.sprite = ButtonSprite; img.type = Image.Type.Sliced; img.color = Color.white; }
        }

        /// <summary>Rounded progress bar; returns the fill Image (set fillAmount via rect width).</summary>
        public static Image MakeBar(Transform parent, string name, out RectTransform fillRect,
            Color? fillColor = null)
        {
            var bgGo = new GameObject(name);
            var bgRt = bgGo.AddComponent<RectTransform>();
            bgRt.SetParent(parent, false);
            var bgImg = bgGo.AddComponent<Image>();
            if (BarSprite != null) { bgImg.sprite = BarSprite; bgImg.type = Image.Type.Sliced; }
            bgImg.color = BarBg;

            var fillGo = new GameObject("Fill");
            fillRect = fillGo.AddComponent<RectTransform>();
            fillRect.SetParent(bgRt, false);
            fillRect.anchorMin = new Vector2(0f, 0f);
            fillRect.anchorMax = new Vector2(0f, 1f);
            fillRect.pivot = new Vector2(0f, 0.5f);
            fillRect.offsetMin = new Vector2(3f, 3f);
            fillRect.offsetMax = new Vector2(3f, -3f);
            var fillImg = fillGo.AddComponent<Image>();
            if (BarSprite != null) { fillImg.sprite = BarSprite; fillImg.type = Image.Type.Sliced; }
            fillImg.color = fillColor ?? Gold;
            return fillImg;
        }

        /// <summary>Thin horizontal divider line.</summary>
        public static void MakeDivider(Transform parent)
        {
            var go = new GameObject("Divider");
            var rt = go.AddComponent<RectTransform>();
            rt.SetParent(parent, false);
            rt.sizeDelta = new Vector2(0f, 2f);
            var img = go.AddComponent<Image>();
            img.color = new Color(1f, 1f, 1f, 0.08f);
        }
    }
}
